database:
  user: creditcardfraud
  password: shankar123
  host: localhost
  port: 1521
  service_name: ORCLPDB

sql:
  tablename: frauddetection

logging:
  path: logs/
  training: training.log
  application: application.log
  level: INFO

model:
  name: credit_card_fraud
  save_path: models/

training:
  cv: 3
  scoring: roc_auc

columns:
  scaling: ['AMOUNT']

parameter_grid:
  n_estimators: [50, 100]
  max_depth: [5, 10]
  min_samples_leaf: [1, 5]
  class_weight: ['balanced']
  scoring: roc_auc
  cv: 3
  n_jobs: 1

prediction:
  column: CLASS

dataPath:
  file: fraud.csv
  path: data/

###to use the database use this key word DBRUN
run:
  runtype: DBRUN

features:
  numerical:
    - TIME
    - V1
    - V2
    - V3
    - V4
    - V5
    - V6
    - V7
    - V8
    - V9
    - V10
    - V11
    - V12
    - V13
    - V14
    - V15
    - V16
    - V17
    - V18
    - V19
    - V20
    - V21
    - V22
    - V23
    - V24
    - V25
    - V26
    - V27
    - V28
    - AMOUNT